<a href="https://colab.research.google.com/github/Laxita-k-jain/Meta-Learning/blob/main/Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1

## Objectives
The Objectives of this week are mainly learning and getting familiar with python and important modules for the purpose of Data Analysis and Machine Learning. We shall cover three main modules in this week. 
1. **NumPy** : The computing module. It eases various common algebraic operations such as matrix/vector multiplication, inverse, powers, calculating mean, variance, etc. 
2. **Scipy** : This as the name suggests is the scientific module. It eases operations such as calculating derivatives of functions, scaling and normalization. 
3. **MatPlotLib** : The plotting module. This helps us to plot various types of plots, histograms, line charts and many more. 

## Problems

Consider a matrix of size 100x50. Initially all the entries in the matrix are 0's. Then **two random** entries in the matrix are set to 1. Now we perform the following steps till all the entries of the matrix have not become 1's : 
1. take **any four random positions** in the matrix and swap them with four other random positions in the matrix. 
2. Now for all the entries in the matrix which are 1's each of it's neighbors has a **0.25 probability** of becoming 1.

Count the number of iterations it takes for the process to terminate.
Plot a curve of number of 1's in a matrix vs the iteration count.  
Repeat this process multiple times and check the number of iterations each time. 
Submission format : Download the python notebook as a python file. Download all the graphs mentioned here. Create a text file reporting the number of iterations for each run. Submit all this in a single directory. 

**Point to ponder** : Does this look like a very simple simulation to the COVID pandemic?






In [16]:
from numpy import random
x = random.randint(1, size=(100, 50))
#print(x)
i = random.randint(1,100)
j = random.randint(1,50)
x[i][j]=1
i = random.randint(1,100)
j = random.randint(1,50)
x[i][j]=1
#print(x)
b=0
s=0
while b==0 :
 s=s+1
 b=1  
 for i in range(1,100):
  for j in range(1,50):
    if x[i][j]==0 :
      b=0
 for k in range(4):
  i = random.randint(1,100)
  j = random.randint(1,50)
  n=x[i][j]
  k = random.randint(1,100)
  l = random.randint(1,50)
  m=x[k][l]
  x[k][l]=n
  x[i][j]=m

 for i in range(100):
  for j in range(50):
    if x[i][j]==1 :
      if random.random() < 0.25:
        if (i!=0):
          x[i-1][j] = 1
      if random.random() < 0.25:
        if (j!=0):
          x[i][j-1] = 1
      if random.random() < 0.25:
        if (i!=99):
         x[i+1][j] = 1  
      if random.random() < 0.25:
        if (j!=49):
         x[i][j+1] = 1

print(x)
print(s)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
51


Consider the image 1.jpg given to you. Color this image:
1. With the most frequently occuring pixel color
2. With the least frequently occuring pixel color
3. With the mean of all pixel colors
**bold text**

Submission Format : Submit all the three images in a single directory. 